strictness: veryhigh

doc-warnings: false
member-warnings: true
test-warnings: true

ignore-paths:
    - settings

ignore-patterns:
    - migrations/

uses:
    - django
    - celery

pep8:
    options:
        max-line-length: 120

pylint:
    options:
        include-naming-hint: y
        max-line-length: 120
