version: '2'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile-django
        container_name: {{ cookiecutter.repo_name }}_django
        volumes:
            - "./static/public:/files/public:ro"
        links:
            - postgres:service_postgres
        depends_on:
            - redis

    postgres:
        image: "postgres:9.6.1"
        container_name: {{ cookiecutter.repo_name }}_postgres
        volumes:
            - "./.data-postgres:/var/lib/postgresql/data"

    celery:
        build:
            context: .
            dockerfile: Dockerfile-django
        container_name: {{ cookiecutter.repo_name }}_celery
        volumes:
            - "./{{ cookiecutter.repo_name }}:/app/{{ cookiecutter.repo_name }}:ro"
        links:
            - postgres:service_postgres
        depends_on:
            - redis
        command: celery worker --app {{ cookiecutter.repo_name }} --loglevel INFO

    celery_beat:
        build:
            context: .
            dockerfile: Dockerfile-django
        container_name: {{ cookiecutter.repo_name }}_celery_beat
        volumes:
            - "./{{ cookiecutter.repo_name }}:/app/{{ cookiecutter.repo_name }}:ro"
            - ".data-celery/:/app/celery"
        links:
            - postgres:service_postgres
        depends_on:
            - redis
        command: celery beat --app {{ cookiecutter.repo_name }} --loglevel INFO --pidfile /app/celery/celerybeat.pid --schedule /app/celery/celerybeat-schedule

    redis:
        image: "redis:3.2.6"
        container_name: {{ cookiecutter.repo_name }}_redis
