version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: "${IMAGE_NAME_APP}:${VERSION}"
    container_name: {{ cookiecutter.repo_name }}_app
    volumes:
      - "./{{ cookiecutter.repo_name }}:/app/{{ cookiecutter.repo_name }}:ro"
      - "./static/public:/files/public:ro"
    external_links:
      - service_postgres
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: "${IMAGE_NAME_APP}:${VERSION}"
    container_name: {{ cookiecutter.repo_name }}_celery
    volumes:
      - "./{{ cookiecutter.repo_name }}:/app/{{ cookiecutter.repo_name }}:ro"
    external_links:
      - service_postgres
    depends_on:
      - redis
    command: celery worker --app {{ cookiecutter.repo_name }} --loglevel INFO

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: "${IMAGE_NAME_APP}:${VERSION}"
    container_name: {{ cookiecutter.repo_name }}_celery_beat
    volumes:
      - "./{{ cookiecutter.repo_name }}:/app/{{ cookiecutter.repo_name }}:ro"
      - ".data-celery/:/app/celery"
    external_links:
      - service_postgres
    depends_on:
      - redis
    command: celery worker -A {{ cookiecutter.repo_name }} -l info -B

  redis:
    image: "redis:3.0.7"
    container_name: {{ cookiecutter.repo_name }}_redis

networks:
  default:
    external:
      name: private
