version: '2'

services:
    django:
        restart: unless-stopped
        volumes:
            - "./{{ cookiecutter.repo_name }}:/app/{{ cookiecutter.repo_name }}:ro"
            - "/volumes/docker-nginx/files/{{ cookiecutter.repo_name }}/media:/files/media"
            - "/volumes/docker-nginx/files/{{ cookiecutter.repo_name }}/static:/files/static"
            - "./.data-logs:/var/log/{{ cookiecutter.repo_name }}"
        command: /usr/local/bin/gunicorn {{ cookiecutter.repo_name }}.wsgi:application --workers 2 --bind :80
    postgres:
        restart: unless-stopped
    celery:
        restart: unless-stopped
        volumes:
            - "./.data-logs:/var/log/{{ cookiecutter.repo_name }}"
    celery_beat:
        restart: unless-stopped
        volumes:
            - "./.data-logs:/var/log/{{ cookiecutter.repo_name }}"
    redis:
        restart: unless-stopped
        command: redis-server --appendonly yes
        volumes:
            - "./.data-redis:/data"

networks:
    default:
        external:
            name: private
