FROM python:3.6.4-slim

EXPOSE 8000

# Install system requirements
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends gcc gettext libpq-dev && \
	rm -rf /var/lib/apt/lists/*

# Install a newer version of pip
RUN pip install --upgrade pip

# Create a directory for the logs
RUN mkdir -p /var/log/{{ cookiecutter.repo_name }}

# Copy script for check the availability of services
COPY wait-for-it.sh /usr/bin/

# Copy requirements
COPY requirements.txt /app/requirements.txt

# Install Python requirements
RUN pip install -r /app/requirements.txt

# Set the default directory where CMD will execute
WORKDIR /app/{{ cookiecutter.repo_name }}

# Set the default command to execute when creating a new container
CMD python manage.py runserver 0.0.0.0:8000
