version: '2'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile-django
        container_name: {{ cookiecutter.repo_name }}_django
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        volumes:
            - "./static/public:/files/public:ro"
        depends_on:
            - postgres
            - redis

    postgres:
        image: "postgres:9.6.1"
        volumes:
            - "./.data-postgres:/var/lib/postgresql/data"

    celery:
        build:
            context: .
            dockerfile: Dockerfile-django
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        volumes:
            - "./{{ cookiecutter.repo_name }}:/app/{{ cookiecutter.repo_name }}:ro"
        depends_on:
            - postgres
            - redis
        command: celery worker --app {{ cookiecutter.repo_name }} --autoscale 10,3 --loglevel INFO

    celery_beat:
        build:
            context: .
            dockerfile: Dockerfile-django
        volumes:
            - "./{{ cookiecutter.repo_name }}:/app/{{ cookiecutter.repo_name }}:ro"
            - ".data-celery/:/app/celery"
        depends_on:
            - redis
        command: celery beat --app {{ cookiecutter.repo_name }} --loglevel INFO --pidfile /app/celery/celerybeat.pid --schedule /app/celery/celerybeat-schedule

    redis:
        image: "redis:3.2.6"
