version: '2'

services:
    django:
        ports:
            - "8000:8000"
        volumes:
            - "./{{ cookiecutter.repo_name }}:/app/{{ cookiecutter.repo_name }}"
            - "./.data-media:/files/media"
            - "./.data-ipython:/root/.ipython"
            # Add static files to the container to get the translations
            - "./static:/app/static:ro"
        environment:
            - PYTHONUNBUFFERED=0
        depends_on:
            - node
        command: python manage.py runserver 0.0.0.0:8000
#        command: /usr/local/bin/gunicorn {{ cookiecutter.repo_name }}.wsgi:application -b :8000 --reload

    node:
        build:
            context: .
            dockerfile: Dockerfile-node
        volumes:
            - "./static/public:/static/public"
            - "./static/src:/static/src:ro"
        command: npm run dev
